services:
  backend:
    container_name: server
    build:
      context: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/server
    networks:
      - graphql_network
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - graphql_network

volumes:
  mongo_data:
    name: mongo_data

networks:
  graphql_network:
    name: graphql_network
